### ISSUE TITLE
Running build:electron on freshly generated Hello World extension fails

### ISSUE THREAD

**Issue by cgudrian** [eclipse-theia/generator-theia-extension#200]
```
$ yarn build:electron
yarn run v1.22.22
$ yarn --cwd electron-app bundle
$ yarn rebuild && theia build --mode development
$ theia rebuild:electron --cacheRoot ..
native node modules are already rebuilt for electron
Updated dependencies, please run "install" again
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
verbose 1.295303889 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/home/christian/.asdf/installs/nodejs/20.8.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/home/christian/.asdf/installs/nodejs/20.8.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/home/christian/.asdf/installs/nodejs/20.8.1/lib/node_modules/yarn/lib/cli.js:790:113)
    at /home/christian/.asdf/installs/nodejs/20.8.1/lib/node_modules/yarn/lib/cli.js:34408:30
    at Generator.throw (<anonymous>)
    at step (/home/christian/.asdf/installs/nodejs/20.8.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/christian/.asdf/installs/nodejs/20.8.1/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I'm on Fedora 40 using Node 20.8.1.

**Comment by JonasHelming** [comment]
Thank you for the report, my PR updates the Electron version to 30.1.2 which fixes the issue
