### ISSUE TITLE
hello-world example does not start

### ISSUE THREAD

**Issue by Coffeesink** [eclipse-theia/generator-theia-extension#236]
Trying to start the hello-world example results in this error message:

yarn start:browser
yarn run v1.22.22
$ yarn --cwd browser-app start
$ theia start

Error: The number of constructor arguments in the derived class NodeStopwatch must be >= than the number of constructor arguments of its base class.
    at C:\projects\my-theia-app-tmp3\browser-app\lib\backend\vendors-node_modules_theia_core_lib_common_index_js.js:10778:27
    at Array.forEach (<anonymous>)
    at _createSubRequests (C:\projects\my-theia-app-tmp3\browser-app\lib\backend\vendors-node_modules_theia_core_lib_common_index_js.js:10760:20)
    at C:\projects\my-theia-app-tmp3\browser-app\lib\backend\vendors-node_modules_theia_core_lib_common_index_js.js:10782:17
    at Array.forEach (<anonymous>)
    at C:\projects\my-theia-app-tmp3\browser-app\lib\backend\vendors-node_modules_theia_core_lib_common_index_js.js:10781:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (C:\projects\my-theia-app-tmp3\browser-app\lib\backend\vendors-node_modules_theia_core_lib_common_index_js.js:10760:20)
    at plan (C:\projects\my-theia-app-tmp3\browser-app\lib\backend\vendors-node_modules_theia_core_lib_common_index_js.js:10803:9)
    at C:\projects\my-theia-app-tmp3\browser-app\lib\backend\vendors-node_modules_theia_core_lib_common_index_js.js:9995:46

Using 
- OS: Windows 10
- Node v21.7.3
- yarn 1.22.22

I tried many other versions with the same result.
[yarn-lock.zip](https://github.com/user-attachments/files/17791689/yarn-lock.zip)

**Comment by Coffeesink** [comment]
Thank you very much!

Mark Sujew ***@***.***> schrieb am So., 17. Nov. 2024, 18:34:
